### PR TITLE
Update Youtue-dl to 2020.03.06

### PR DESCRIPTION
**Pull request by Eonfge**

### CODE REVIEW

**Comment by Eonfge** [comment]
@bilelmoussaoui Here you go again

**Comment by bilelmoussaoui** [comment]
@Eonfge do you mind if I give you write access to the repository ? :) you update way more often than I do

**Comment by Eonfge** [comment]
@bilelmoussaoui No problem. Lollypop is one of the apps I care a lot about, so I would like to help where I can.

**Comment by bilelmoussaoui** [comment]
Done, thanks a lot for the help :+1:

**Pull request merged**
