### PR TITLE
Updated Lollypop, YouTube-dl and python modules

### PR DESCRIPTION
**Pull request by Eonfge**
I did not update the gstreamer plugins because they require a runtime update first

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
You can remove both gst plugins as they are part of FreeDesktop 19.08.

**Comment by bilelmoussaoui** [comment]
Upstream have a requirements.txt, might worth generating the dependencies using flatpak-builder-tools

**Comment by Eonfge** [comment]
@bilelmoussaoui I looked at the requirements.text but it's a bit of a mess. Some of the original requirements were never in it for example. It was also never updated during the 1.2.0 development.

The builder does seem to have all required libs:
```
The Meson build system
Version: 0.50.1
Source dir: /run/build/lollypop
Build dir: /run/build/lollypop/_flatpak_build
Build type: native build
Project name: lollypop
Project version: 1.2.2
Build machine cpu family: x86_64
Build machine cpu: x86_64
DEPRECATION: Project targetting '>= 0.40.0' but tried to use feature deprecated since '0.48.0': python3 module
Message: Looking for dependencies
Message: Found python3 binary
Found pkg-config: /usr/bin/pkg-config (1.6.0)
Dependency gobject-introspection-1.0 found: YES 1.60.2
Dependency gtk+-3.0 found: YES 3.24.11
Dependency libsoup-2.4 found: YES 2.66.3
Dependency glib-2.0 found: YES 2.60.7
Dependency pygobject-3.0 found: YES 3.32.2
Message: Compiling resources
Configuring AboutDialog.ui using configuration
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Message: Installing man-page
Message: Making a list of icons

|Executing subproject po 
|
|Project name: lollypop-po
|Project version: undefined
|Message: Update translations
|Build targets in project: 6
|Subproject po finished.

Configuring lollypop-sp using configuration
Configuring org.gnome.Lollypop.SearchProvider.service using configuration
Message: Preparing init file
Configuring lollypop using configuration
Program meson_post_install.py found: YES (/usr/bin/env python3 /run/build/lollypop/meson_post_install.py)
Build targets in project: 6
WARNING: Deprecated features used:
 * 0.48.0: {'python3 module'}
Found ninja-1.9.0 at /usr/bin/ninja
```

**Comment by bilelmoussaoui** [comment]
Right. Thanks!

**Comment by Eonfge** [comment]
@bilelmoussaoui Hold the pressed! I spotted an error myself. The current runtime is still 3.32. Allow me to make a quick new pull request. If you look at the log i quoted, you can actually see it using ` pygobject-3.32.2`

**Comment by Eonfge** [comment]
Edit, never mind, was only the local version that I build against the wrong runtime. Everything seems fine

**Pull request merged**
